# steps:
#   - ...
#   - uses: docker-library/bashbrew
#   - ...

name: 'Install Bashbrew'
description: 'Install the "bashbrew" tool in GITHUB_PATH'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: '${{ github.action_path }}/go.mod'
    - run: |
        '${{ github.action_path }}/bashbrew.sh' --version > /dev/null
        '${{ github.action_path }}/bin/bashbrew' --version
        echo '${{ github.action_path }}/bin' >> "$GITHUB_PATH"
        echo 'BASHBREW_SCRIPTS=${{ github.action_path }}/scripts' >> "$GITHUB_ENV"
      shell: 'bash -Eeuo pipefail -x {0}'
