FROM golang:1.24-trixie

SHELL ["bash", "-Eeuo", "pipefail", "-xc"]

WORKDIR /usr/src/bashbrew

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go test -v -race -coverprofile=coverage.out ./...

RUN go tool cover -func=coverage.out
